# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71146f70db2ca5ffe86bb79909442f393788c4a675dcff1eb0396fd6d0b32840505b95af7b78200b050f2e0f49d97b6b6a81c9a60c8280fe607241541963bf69

test:
  secret_key_base: 5cafb751cdf0024a6d0bdde9a823a32064d93a47902ff6ae362e8cdc638dee5f0fe79aabada3a0bf654c966284b892f8950e263187ebf40f8ee4664215f05faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
